permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: "Genevieve Lepine"
  description: |
    A showcase of my portfolio, highlighting my work in the area of branding and corporate identity.
  font_url: "https://fonts.googleapis.com/css?family=Oswald:300,400,600,700"
  colors:
    background: "--color-secondary-opposite"
    accent: "--color-secondary"

    patterns:
      brand.logos: "--color-secondary-opposite"
      navigations.social-media-nav: "--color-primary"
      navigations.main-footer-nav: "--color-primary"

  rationales:
    colors.primary: |
      The primary colour represents the serious, ordered aspects of my personality. The primary colour is used for most text, except for buttons and hover-state buttons, the footer, where text is reversed out on a dark background, and some of the placeholder text inside the form fields on the checkout form.

    colors.secondary: |
      The secondary colours represents the creative, playful aspects of my personality. The darker secondary colour is used as a background color on every button related to purchasing an item. The dark secondary colour is also used for the logo and iconography, as well as the rating system. The lighter secondary colour is used sparingly, as dividing elements on several pages.

    typefaces.primary: |
      The primary typeface is serious and legible. It is to be used for all body copy.

    typefaces.secondary: |
      The secondary typeface is narrow and playful, and is to be used for headings.

    colors.accent: |
      The accent colours have been chosen to provide contrast and pops of colour to the page. The dark accent colour is to be used for buttons in the form and for the footer..

    layouts:
      default: |
        The default layout should be used for almost every page. It includes the website's primary header and footer.

collections:
  products:
    output: true
  sketches:
    output: true
  other-work:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
  - scope:
      path: _sketches
    values:
      layout: sketch
  - scope:
      path: _other-work
    values:
      layout: other-work
