title: "Sections"
description: |
  Sections are used to present groups of similar content.

patterns:
  basic-section:
    title: "Basic section"
    description: |
      Basic sections are used to present content such as the background story of the store. It should be used on the homepage.

  introduction-text:
    title: "Introduction text"
    description: |
      This section is used for a block of text that introduces content on a page and serves to separate content.
    fields:
      - name: text
        type: string
        example: "Take a look at some of my favourite projects and case studies below."
      - name: text
        type: string
        example: "Have a look at some of my favourite personal projects below."
      - name: text
        type: string
        example: "I'd also love to show you some of my favourite personal projects. Have a look!"
